FROM php:%%BASE_IMAGE_TAG%%

RUN apt-get update && apt-get install -y git && apt-get -y autoremove && apt-get -y autoclean
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /bin/composer
RUN composer global require hirak/prestissimo


